# Generated by Django 5.0.6 on 2024-05-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emprestimolivro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmprestimoLivro',
        ),
    ]
