# Generated by Django 5.0.6 on 2024-05-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_id_livro_emprestimo_livro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataHora',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoriaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livroCategoria', to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='usuarioFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livroAutor', to='app.usuariocustomizado'),
        ),
    ]
