# Generated by Django 5.0.6 on 2024-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='id_livro',
            new_name='livro',
        ),
        migrations.AddField(
            model_name='usuariocustomizado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariocustomizado',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
